# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: npm install

      - name: Lint Test
        run: npm run lint

      - name: AoT Build
        run: npm run build:aot
